name: lint-test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: "ubuntu-latest"
    name: "Run"
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          cache: npm
          node-version: 20

      - name: npm ci
        run: |
          npm ci

      - name: Format Check
        run: npm run format-check

      - name: Verify
        run: |
          npm run build
          # Fail if "npm run build" generated new changes in dist
          git update-index --refresh dist/* && git diff-index --quiet HEAD dist

      - name: Test
        run: npm run test
