name: lint-test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: "ubuntu-latest"
    name: "Run"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: npm
          node-version: 20

      - name: npm ci
        run: |
          npm ci

      - name: Format Check
        run: npm run format-check

      - name: Verify
        run: |
          npm run build
          # Fail if "npm run build" generated new changes in dist
          git update-index --refresh dist/* && git diff-index --quiet HEAD dist

      - name: Test
        run: npm run test
